"""Focused checks for the installed-package Hermes smoke helper."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from scripts import check_hermes_package_smoke


def test_agent_message_texts_for_turn_requires_matching_turn_and_type() -> None:
    transcript: list[object] = [
        {
            "turn_id": "synthetic-turn-1",
            "type": "agentMessage",
            "text": "DIS88-SYNTHETIC-FIRST-MARKER",
        },
        {
            "turn_id": "synthetic-turn-2",
            "type": "userMessage",
            "text": "DIS88-SYNTHETIC-FIRST-MARKER",
        },
        {
            "turn_id": "synthetic-turn-2",
            "type": "agentMessage",
            "text": "recalled DIS88-SYNTHETIC-FIRST-MARKER",
        },
        {
            "turn_id": "synthetic-turn-2",
            "type": "agentMessage",
            "text": None,
        },
        "invalid item",
    ]

    assert check_hermes_package_smoke._agent_message_texts_for_turn(
        transcript, "synthetic-turn-2"
    ) == ["recalled DIS88-SYNTHETIC-FIRST-MARKER"]


def test_source_dirty_fails_when_git_status_fails(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def fail_status(argv: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(argv, 128, stdout="", stderr="fatal: not a repository")

    monkeypatch.setattr(subprocess, "run", fail_status)

    with pytest.raises(check_hermes_package_smoke.SmokeFailure, match="git status failed"):
        check_hermes_package_smoke._source_dirty(tmp_path)


def test_source_git_probes_clear_inherited_repository_selectors(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls: list[dict[str, str]] = []

    def record_run(argv: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        env = kwargs.get("env")
        assert isinstance(env, dict)
        calls.append(env)
        stdout = "revision\n" if argv[1] == "rev-parse" else ""
        return subprocess.CompletedProcess(argv, 0, stdout=stdout, stderr="")

    for name in check_hermes_package_smoke._GIT_REPOSITORY_SELECTORS:
        monkeypatch.setenv(name, f"inherited-{name}")
    monkeypatch.setenv("KEEP_ME", "present")
    monkeypatch.setattr(subprocess, "run", record_run)

    assert check_hermes_package_smoke._source_revision(tmp_path) == "revision"
    assert check_hermes_package_smoke._source_dirty(tmp_path) is False
    assert len(calls) == 2
    assert all(env.get("KEEP_ME") == "present" for env in calls)
    assert all(
        selector not in env
        for env in calls
        for selector in check_hermes_package_smoke._GIT_REPOSITORY_SELECTORS
    )


def test_tree_sha256_ignores_python_bytecode_and_cache_artifacts(tmp_path: Path) -> None:
    (tmp_path / "entry.py").write_text("print('source')\n")
    expected = check_hermes_package_smoke._tree_sha256(tmp_path)

    cache = tmp_path / "__pycache__"
    cache.mkdir()
    (cache / "entry.cpython-313.pyc").write_bytes(b"generated bytecode")
    (tmp_path / "orphan.pyc").write_bytes(b"generated bytecode")
    pytest_cache = tmp_path / ".pytest_cache"
    pytest_cache.mkdir()
    (pytest_cache / "README.md").write_text("generated cache\n")

    assert check_hermes_package_smoke._tree_sha256(tmp_path) == expected


def test_readme_hermes_operator_guide_anchor_exists() -> None:
    repository = Path(__file__).parents[1]

    assert "(docs/usage/README.md#hermes-owned-sessions)" in (repository / "README.md").read_text()
    assert "\n### Hermes Owned Sessions\n" in (repository / "docs/usage/README.md").read_text()


def test_parse_args_builds_from_checkout_unless_wheel_is_supplied() -> None:
    assert check_hermes_package_smoke._parse_args([]).wheel is None
    assert check_hermes_package_smoke._parse_args(["--", "--wheel", "dist/x.whl"]).wheel == Path(
        "dist/x.whl"
    )


def test_source_evidence_for_supplied_wheel_does_not_claim_head(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def forbid_run(argv: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        raise AssertionError(f"supplied wheel must not probe git: {argv}")

    monkeypatch.setattr(subprocess, "run", forbid_run)

    assert check_hermes_package_smoke._source_evidence(tmp_path, built_from_checkout=False) == {
        "revision": None,
        "dirty": None,
        "revision_binding": "unverified",
    }


def test_source_evidence_for_checkout_build_records_head(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def fake_run(argv: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        stdout = "abc123\n" if argv[1] == "rev-parse" else " M file\n"
        return subprocess.CompletedProcess(argv, 0, stdout=stdout, stderr="")

    monkeypatch.setattr(subprocess, "run", fake_run)

    assert check_hermes_package_smoke._source_evidence(tmp_path, built_from_checkout=True) == {
        "revision": "abc123",
        "dirty": True,
        "revision_binding": "checkout_build",
    }


def test_build_wheel_builds_the_anchored_checkout_into_out_dir(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    repository = tmp_path / "checkout"
    out_dir = tmp_path / "build"
    calls: list[list[str]] = []

    def fake_command(argv: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append(argv)
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "outfitter_dispatch-0.0.0-py3-none-any.whl").write_bytes(b"wheel")
        return subprocess.CompletedProcess(argv, 0, stdout="", stderr="")

    monkeypatch.setattr(check_hermes_package_smoke, "_uv", lambda: "/usr/bin/uv")
    monkeypatch.setattr(check_hermes_package_smoke, "_command", fake_command)

    wheel = check_hermes_package_smoke._build_wheel(repository, out_dir)

    assert wheel == out_dir / "outfitter_dispatch-0.0.0-py3-none-any.whl"
    assert calls == [
        ["/usr/bin/uv", "build", "--wheel", "--out-dir", str(out_dir), str(repository)]
    ]


def test_build_wheel_requires_exactly_one_built_wheel(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def fake_command(argv: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(argv, 0, stdout="", stderr="")

    monkeypatch.setattr(check_hermes_package_smoke, "_uv", lambda: "/usr/bin/uv")
    monkeypatch.setattr(check_hermes_package_smoke, "_command", fake_command)

    with pytest.raises(check_hermes_package_smoke.SmokeFailure, match="produced 0 wheels"):
        check_hermes_package_smoke._build_wheel(tmp_path / "checkout", tmp_path / "build")
