"""Regenerate src/outfitter/dispatch/contracts/legacy_baseline.py.

Run this when cutting a release, when the current tree IS the new parent:

    uv run python scripts/gen_legacy_baseline.py --parent-version X.Y.Z

That snapshots every op's current schema hash and resets CHANGED_SINCE_PARENT
to empty. During development, do NOT regenerate to silence the baseline test —
add the drifted op id to CHANGED_SINCE_PARENT in legacy_baseline.py by hand
instead (a conscious, reviewable declaration that the op is unsafe to forward
to the parent-release daemon). ``--changed``/``--note`` exist for the rare
regeneration mid-cycle, when the excluded ops' current hashes already differ
from the parent's.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from outfitter.dispatch.contracts.legacy_baseline import READ_BASELINE_FLOOR
from outfitter.dispatch.contracts.registry import op_schema_hash
from outfitter.dispatch.core.ops import REGISTRY

TARGET = Path("src/outfitter/dispatch/contracts/legacy_baseline.py")

HEADER = '''"""Parent-release op-schema baseline (hashes GENERATED — do not hand-edit them).

Regenerated by ``scripts/gen_legacy_baseline.py`` at release cut. Between
releases, only :data:`CHANGED_SINCE_PARENT` is edited (by hand): when an op's
input/output schema drifts from the parent release, the baseline test fails
until the op id is added there — a conscious, reviewable declaration that the
op must not be forwarded to a pre-handshake parent-release daemon.

An op listed here with its parent hash is provably parsed identically by the
parent release, so clients may forward it even to a daemon that predates the
op-schema handshake (see ``registry_legacy_safe_ops``).
{note}"""

PARENT_VERSION = "{parent_version}"
"""The immediate parent release these hashes were taken from."""

READ_BASELINE_FLOOR = "{read_floor}"
"""Oldest metadata-capable release whose read-safe op schemas all match current.

A pre-handshake daemon (reports ``version`` but no ``op_schemas``) may serve
read-safe ops only when it self-reports at least this version
(:func:`outfitter.dispatch.contracts.registry.prehandshake_op_allowed`).
Established from released-sdist schema evidence (see the PR that introduced
it); bump it via ``--read-floor`` to the first release carrying the new schema
whenever a read-safe op's input/output schema changes."""

CHANGED_SINCE_PARENT: frozenset[str] = frozenset({changed})
"""Ops whose input/output schema drifted since ``PARENT_VERSION``.

Never forwarded to a pre-handshake daemon: its Pydantic models (default
``extra="ignore"``) would silently drop the fields that changed.
"""

PARENT_OP_SCHEMA_HASHES: dict[str, str] = {{
{hashes}}}
"""Per-op schema fingerprints of the parent release (op id → sha256)."""
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--parent-version", required=True)
    parser.add_argument(
        "--changed",
        default="",
        help="Comma-separated op ids changed since the parent (omitted from the hash table).",
    )
    parser.add_argument(
        "--note",
        default="",
        help="Extra docstring paragraph recording why this baseline is trustworthy.",
    )
    parser.add_argument(
        "--read-floor",
        default=READ_BASELINE_FLOOR,
        help=(
            "Oldest release whose read-safe op schemas all match current "
            "(defaults to the currently recorded READ_BASELINE_FLOOR; bump when "
            "a read-safe op's schema changed since that release)."
        ),
    )
    args = parser.parse_args()

    changed = sorted({op_id for op_id in args.changed.split(",") if op_id})
    unknown = [op_id for op_id in changed if op_id not in set(REGISTRY.ids())]
    if unknown:
        raise SystemExit(f"--changed names unknown ops: {', '.join(unknown)}")

    hashes = "".join(
        f'    "{op.id}": "{op_schema_hash(op)}",\n' for op in REGISTRY if op.id not in changed
    )
    changed_literal = "{" + ", ".join(f'"{op_id}"' for op_id in changed) + "}" if changed else "()"
    note = f"\n{args.note}\n" if args.note else ""
    TARGET.write_text(
        HEADER.format(
            parent_version=args.parent_version,
            read_floor=args.read_floor,
            changed=changed_literal,
            hashes=hashes,
            note=note,
        )
    )
    print(f"wrote {TARGET} ({len(REGISTRY) - len(changed)} hashes, {len(changed)} changed)")


if __name__ == "__main__":
    main()
