"""Parent-release op-schema baseline (hashes GENERATED — do not hand-edit them).

Regenerated by ``scripts/gen_legacy_baseline.py`` at release cut. Between
releases, only :data:`CHANGED_SINCE_PARENT` is edited (by hand): when an op's
input/output schema drifts from the parent release, the baseline test fails
until the op id is added there — a conscious, reviewable declaration that the
op must not be forwarded to a pre-handshake parent-release daemon.

An op listed here with its parent hash is provably parsed identically by the
parent release — and ONLY that release. Clients may forward it to a
pre-handshake daemon only when that daemon self-reports exactly
``PARENT_VERSION`` in ``__dispatch/metadata`` (see ``registry_legacy_safe_ops``
and ``prehandshake_op_allowed``); older releases' schemas may differ from the
baseline (e.g. v0.8.2's ``send`` had no ``content`` field).

Baseline for parent v0.11.0 (main): computed from the current tree rather than
a parent checkout. That is sound because this branch's only schema change
relative to main is the ``provider`` field added to ``NewInput`` (DIS-49),
which is shared by exactly ``new`` and ``new-plan`` — both excluded via
CHANGED_SINCE_PARENT. No other input/output model changed, so every remaining
op's current hash equals the parent's.
"""

PARENT_VERSION = "0.11.0"
"""The immediate parent release these hashes were taken from."""

READ_BASELINE_FLOOR = "0.10.0"
"""Oldest metadata-capable release whose read-safe op schemas all match current.

A pre-handshake daemon (reports ``version`` but no ``op_schemas``) may serve
read-safe ops only when it self-reports at least this version
(:func:`outfitter.dispatch.contracts.registry.prehandshake_op_allowed`).

Evidence (released sdists from PyPI, op input/output ``model_json_schema``
fingerprints computed under one pinned pydantic, compared to current per
read-safe op):

- ``<= 0.8.1`` — no ``__dispatch/metadata`` method at all, and read inputs had
  already drifted (e.g. 0.8.1's ``RosterInput`` only had ``include_archived``,
  so ``roster --parent`` would be silently dropped). Blocked entirely.
- ``0.8.2`` — read inputs match current (``permissions`` absent, which fails
  loudly as method-not-found), but ``roster``/``show`` outputs predate
  ``duration_ms``/``history_*`` and ``usage`` output predates the provider
  runtime summary.
- ``0.9.0`` — only ``usage`` output still drifted (predates the runtime
  summary fields).
- ``0.10.0`` and ``0.11.0`` — every read-safe op's input AND output schema is
  identical to current.

Raise this floor (or regenerate the evidence) whenever a read-safe op's schema
changes; the release-cut baseline test only proves parity with
``PARENT_VERSION``, so a read-op schema change must also bump this floor to
the first release carrying the new schema."""

CHANGED_SINCE_PARENT: frozenset[str] = frozenset({"new", "new-plan"})
"""Ops whose input/output schema drifted since ``PARENT_VERSION``.

Never forwarded to a pre-handshake daemon: its Pydantic models (default
``extra="ignore"``) would silently drop the fields that changed.
"""

PARENT_OP_SCHEMA_HASHES: dict[str, str] = {
    "open": "2e663feeb4533c6838b00a4ff352597abaa3b728b166b3aa2a6ee4f69bcc41d8",
    "attach": "b6897800a0405339e910cf98de8277bac6ad6f1b6b90bd58345182d5c9d21bc9",
    "send": "0a3ff6aca533e074bab606a11f3e473abb2a7fad5d46dc64b5a5de4de76545bb",
    "stop": "16ccc26967a0c253f1cff65f4b8a455f7db38226773d0b0c1cb5f6e2b86e392c",
    "show": "dde8863962e92c7fc562c223ce1bdc7690664279d031af4cdd7bd89b6e99e0c5",
    "lane-rename": "c90f27886bd7bb6a8468f7bc7336716d60525b2361b4e9507d6e9d8b9273cf46",
    "transcript": "d1d2acca3ed46ce7451801aff4c588038e8cd13eea83b5b8e6c8e2a87671b86a",
    "history": "43f8d8689b4171d655a8b14895cbb1af6ffe007aaa93ec14d6be76c19d2e1243",
    "watch": "9febdc5f24bac264900435da630a5c4adb3b63e8da934d58cef5b3750f498fa5",
    "sync": "306c6ddcf8abf3fca5f0509ca85499064b67e8b98eb1db68f9942a1e9b768845",
    "roster": "87b510b96a96157303bd508fd01f26e11da8e31965e3878950504149de71d5d2",
    "discover": "96a284f08bdb3b9c4f15c6a70f5abb0ecf3b5022d7b05ac443a2c8d5377adeb1",
    "search": "6383eb95772eae4ad689ad90c123244f36434f5b884cbe43cfab15075a891c0e",
    "query": "37544d538a1ee55818edcda6b9615db719d35fd8dd4274fc4075fccf5e6b79ba",
    "models": "246d581df042fe34b36c404ab9d75bdce1e678aee1c01662a16b93bb6f997035",
    "permissions": "c9601fe3d928338d3f09d66bfddd705672af66fdcef17f12237ad0244989b03f",
    "usage": "e39b1afb1f34f970cde77645cf62aa9aed23b88c5b7bb1364d2745120640b956",
    "inbox-list": "4acfba2e70657341f9ec36922df8231b1b153b51562ebe599f578b63944c8563",
    "inbox-read": "16f87adad24972261092119efeda7c82ccc082f66403ec2dffb338fc79032444",
    "inbox-ack": "e014aff12612ad410b2b6141db91f7026ce4a118154c797e0df6d386e82f311a",
    "server-request-list": "5e43356a54a95b30d4bc3c1baac6fa114fa51a10064787114d7789841c43968a",
    "server-request-respond": "ca25a261f8e44ae6c7fbc5ed4e7f9cccbd199ac7f1fa6ac566b248df2f4b4370",
    "subscribe": "719fcfc0279dc70e54e8c46493f4da2efd487186e97506390460dd3f6f92cfe2",
    "subscription-list": "bc726c0c399357e0eeb81307dc54cacff4db03c06726933d7428fadf0d045f3c",
    "unsubscribe": "0d2203429b98ed3614707287c4f424f58813c02664aad35743cbb7bbe82eb6da",
    "archive": "164ef5d176c8c1c90a95627bc6695d6f7632b0adf68919d8cccf63599b03a475",
    "restore": "164ef5d176c8c1c90a95627bc6695d6f7632b0adf68919d8cccf63599b03a475",
    "goal-get": "0ff6b7f7467ce48c6afbf39fa7900be67776664783c0c5a9a0bd90e8df06c699",
    "goal-set": "2fcb09ccd7fb2825ad2794d036efe7958f869812df66cc3631613b8bf6a3100f",
    "goal-clear": "2dfb19dbfdc2ad9e10583a7df2cbb01f7988922748caa1d921b6306930afffc5",
    "fork": "3db182e6fed46adc4c4a6c246ba69b39aa86378276c58f1b2cb2f671a7686db6",
    "rollback": "02199e08bfd8f932addf73cf3a328f2d72e40c05fbdcd6f8de95da8ce5af0426",
    "compact": "5aec00f1dd3427fb7368223277dd7310d254b3a7a4252cde4ab5451bf759dca9",
    "status": "4c9f6d7a774c4b4d06d0da9743eb55113c13cc323e6a47f6bbeb3fa94145bc48",
    "log": "fa720f3eb8c816d2045d996ac49b1a51217872215d660566b40e19a6ed1a8d66",
    "trigger-add": "ceef3ef04f635e1bc3af4b9b019e6c7a253d26ef5221fcbacbaa60f1a5950d0f",
    "trigger-list": "069e694fddbfe050c430ba8762a1630b34d4880381d4f8a023e8c788fcb4356a",
    "trigger-rm": "8a4559cd7006c018de4a8a3c5df8e4c115404551cbc8ed7975c4386894533ea8",
    "trigger-pause": "09fec6476a907b4c514473860c39b4d406c55b67155c462577ad53b364198aae",
    "trigger-resume": "09fec6476a907b4c514473860c39b4d406c55b67155c462577ad53b364198aae",
}
"""Per-op schema fingerprints of the parent release (op id → sha256)."""
